# Project Information
site_name: MSA Mapper

# Configuration
theme:
  name: "material"
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  # logo: assets/logo.png

# Plugins
plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter

# Customization
extra:
  generator: false
extra_css: [assets/extra.css]

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Page tree
nav:
  - Home:
    - Overview: home/overview.md
    - Use-Cases: home/use_cases.md
  - Modules:
    - Geographic Decoder: modules/geocoder.md
    - Census MSA Mapping: modules/census_msa.md